# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170922_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='related_tag', to='blog.Tag'),
        ),
    ]
