# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170925_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prof_img',
            field=models.ImageField(blank=True, height_field=150, null=True, upload_to='blog/prof_img', width_field=150),
        ),
    ]
