# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170927_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='q_location',
            field=models.SlugField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
